### ISSUE TITLE
Version 2

### ISSUE THREAD

**Issue by jesusantguerrero** [jesusantguerrero/sunday#97]
It seems like zen is missing features like timer as Toggl and the powerful queries and flexibility of custom tables. Sunday already has that.

And Sunday is missing a better Eisenhower and Pomodoro implementation. Zen already has those battle-tested.

So, let's get serious and combine them.

> The only thing I need to check is Vue 2.7 stability as prev step to migrate to Vue 3 and use the components of Zen

## Roadmap
- [x] Update inertia 0.8 (vue 2) and 0.11
- [x] Update laravel mix 6.
- [x] Add zenboard layout.
- [x] Update to Vue 3
- [x] Update Eisenhower matrix layout.
- [ ] Add metrics from Zen.
- [ ] Add ran but not completed tasks in commit section
- [ ] Add notes
- [x] Add sorting by task name
- [ ] Add sorting by other fields
- [ ] Add stages page and pagination
By the time I complete this Vue 2.7 should be stable.  I'll reevaluate what is next from there.
